autocmd filetype markdown set ts=2
autocmd filetype markdown set sw=2
autocmd filetype markdown set expandtab
autocmd filetype markdown set nolinebreak
autocmd filetype markdown set fdm=indent
autocmd filetype markdown set tw=0
autocmd filetype markdown set smarttab
autocmd filetype markdown set smartindent
autocmd FileType javascript set spell
